# Generated by Django 6.0.1 on 2026-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
