# Generated by Django 6.0.1 on 2026-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_compra_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
