# Generated by Django 6.0.1 on 2026-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_compra_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
