# Generated by Django 6.0.1 on 2026-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.IntegerField(choices=[(21, 'General'), (10, 'Reducido'), (4, 'Superreducido'), (0, 'Excento')], null=True),
        ),
    ]
