# Generated by Django 6.0.1 on 2026-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.IntegerField(),
        ),
    ]
