# Generated by Django 6.0.1 on 2026-01-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_promocion_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
