# Generated by Django 6.0.1 on 2026-01-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_compra_promocion_alter_promocion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.promocion'),
        ),
    ]
